import { createId, getAll, put, remove } from '../database.js';
import { money, dateShort, escapeHTML, initials } from '../formatters.js';
import { requireFields, sanitizeText } from '../validators.js';
import { toast } from '../components/layout.js';

const stages = ['Novo', 'Contactado', 'Qualificado', 'Reunião', 'Proposta enviada', 'Negociação', 'Ganho', 'Perdido'];
const state = { leads: [], clients: [], view: 'kanban', query: '', stage: 'Todos', source: 'Todos', interest: 'Todos', owner: 'Todos', sort: 'createdAt' };
const isLate = (lead) => lead.deadline && !['Ganho', 'Perdido'].includes(lead.stage) && new Date(lead.deadline) < new Date();
const statusClass = (stage) => /Ganho/.test(stage) ? 'success' : /Perdido/.test(stage) ? 'danger' : /Negociação|Proposta|Reunião/.test(stage) ? 'warning' : '';
const splitTags = (value='') => String(value).split(',').map((tag)=>tag.trim()).filter(Boolean);

async function activity(message, entityId) { await put('activities', { id: createId('act'), module: 'leads', entityId, message, createdAt: new Date().toISOString() }); }
function options(values, selected) { return ['Todos', ...new Set(values.filter(Boolean))].map((value) => `<option ${value === selected ? 'selected' : ''}>${escapeHTML(value)}</option>`).join(''); }
function filtered() {
  return state.leads.filter((lead) => [lead.name, lead.company, lead.email, lead.phone, lead.interest, lead.source, lead.owner].join(' ').toLowerCase().includes(state.query.toLowerCase()))
    .filter((lead) => state.stage === 'Todos' || lead.stage === state.stage)
    .filter((lead) => state.source === 'Todos' || lead.source === state.source)
    .filter((lead) => state.interest === 'Todos' || lead.interest === state.interest)
    .filter((lead) => state.owner === 'Todos' || lead.owner === state.owner)
    .sort((a,b) => state.sort === 'value' ? Number(b.estimatedBudget||0)-Number(a.estimatedBudget||0) : new Date(b[state.sort] || 0)-new Date(a[state.sort] || 0));
}
function form(lead={}) { return `<form id="leadForm" novalidate><div class="form-grid">
  ${input('name','Nome *',lead.name)}${input('company','Empresa *',lead.company)}${input('email','Email',lead.email,'email')}${input('phone','Telefone',lead.phone)}${input('whatsapp','WhatsApp',lead.whatsapp)}${input('interest','Serviço de interesse',lead.interest||lead.service)}${input('source','Origem',lead.source)}${input('estimatedBudget','Valor estimado (€)',lead.estimatedBudget||0,'number')}${input('probability','Probabilidade (%)',lead.probability||20,'number')}${input('owner','Responsável',lead.owner||'LOOREBEE')}${input('priority','Prioridade',lead.priority||'Normal')}${input('nextAction','Próxima ação',lead.nextAction)}${input('deadline','Data da próxima ação',lead.deadline,'date')}
  <div class="field"><label for="stage">Estado</label><select id="stage" name="stage">${stages.map((stage)=>`<option ${stage===(lead.stage||'Novo')?'selected':''}>${stage}</option>`).join('')}</select></div>
  <div class="field full"><label for="tags">Etiquetas</label><input id="tags" name="tags" value="${escapeHTML((lead.tags||[]).join ? lead.tags.join(', ') : lead.tags || '')}"></div>
  <div class="field full"><label for="notes">Notas</label><textarea id="notes" name="notes" rows="4">${escapeHTML(lead.notes||'')}</textarea></div>
  </div><div class="actions"><button class="btn" type="button" data-action="close-drawer">Cancelar</button><button class="btn primary" type="submit">Guardar lead</button></div></form>`; }
function input(name,label,value='',type='text'){return `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${escapeHTML(value||'')}"></div>`;}
function drawer(title, body){document.querySelector('.drawer-backdrop')?.remove(); const el=document.createElement('div'); el.className='drawer-backdrop'; el.innerHTML=`<aside class="drawer" role="dialog" aria-modal="true"><div class="drawer-head"><div><span class="badge">Funil comercial</span><h2>${escapeHTML(title)}</h2></div><button class="icon-btn" data-action="close-drawer">✕</button></div>${body}</aside>`; document.body.append(el); el.querySelector('input,button,select,textarea')?.focus();}
function payload(formEl, old={}){const data=Object.fromEntries(new FormData(formEl).entries()); return {...old,id:old.id||createId('lead'),name:sanitizeText(data.name),company:sanitizeText(data.company),email:sanitizeText(data.email),phone:sanitizeText(data.phone),whatsapp:sanitizeText(data.whatsapp),interest:sanitizeText(data.interest),source:sanitizeText(data.source),estimatedBudget:Number(data.estimatedBudget||0),probability:Number(data.probability||0),owner:sanitizeText(data.owner),priority:sanitizeText(data.priority),nextAction:sanitizeText(data.nextAction),deadline:data.deadline,stage:data.stage,notes:sanitizeText(data.notes),tags:splitTags(data.tags),demo:Boolean(old.demo)};}
function openEditor(lead=null, presetStage='Novo'){ drawer(lead?'Editar lead':'Novo lead', form(lead||{stage:presetStage})); document.querySelector('#leadForm').addEventListener('submit', async (e)=>{e.preventDefault(); const item=payload(e.currentTarget,lead||{}); if(Object.keys(requireFields(item,['name','company'])).length){toast('Preencha nome e empresa.', 'error');return;} await put('leads',item); await activity(lead?`Lead atualizado: ${item.company}`:`Lead criado: ${item.company}`,item.id); toast(lead?'Lead atualizado.':'Lead criado.','success'); close(); await load();});}
function kpis(){const total=state.leads.length; const potential=state.leads.reduce((s,l)=>s+Number(l.estimatedBudget||0),0); const won=state.leads.filter(l=>l.stage==='Ganho').length; return [['Total de leads',total,'Oportunidades no funil'],['Valor potencial',money(potential),'Pipeline comercial'],['Taxa de conversão',total?`${Math.round(won/total*100)}%`:'0%','Leads ganhos'],['Ações atrasadas',state.leads.filter(isLate).length,'Follow-ups vencidos']];}
function card(lead){return `<article class="kanban-card" draggable="true" data-id="${lead.id}"><div class="identity"><span class="avatar">${escapeHTML(initials(lead.company||lead.name))}</span><div><strong>${escapeHTML(lead.name)}</strong><br><span class="text-secondary">${escapeHTML(lead.company)}</span></div></div><div class="card-meta"><span>${escapeHTML(lead.interest||'Serviço')}</span><span>${escapeHTML(lead.source||'Origem')}</span><span>${money(lead.estimatedBudget)}</span></div><div class="list-row"><span>${escapeHTML(lead.nextAction||'Sem próxima ação')}</span><strong class="${isLate(lead)?'danger-text':''}">${dateShort(lead.deadline)}</strong></div><div>${splitTags((lead.tags||[]).join ? lead.tags.join(',') : lead.tags).map(t=>`<span class="tag">${escapeHTML(t)}</span>`).join(' ')}</div><div class="actions"><button class="icon-btn" data-action="view-lead" data-id="${lead.id}">Ver</button><button class="icon-btn" data-action="convert-lead" data-id="${lead.id}">Converter</button></div></article>`;}
function renderKanban(leads){return `<div class="kanban-board">${stages.map(stage=>{const items=leads.filter(l=>l.stage===stage); return `<section class="kanban-column" data-stage="${stage}"><div class="kanban-head"><div><h3>${stage}</h3><div class="kanban-total">${items.length} · ${money(items.reduce((s,l)=>s+Number(l.estimatedBudget||0),0))}</div></div><button class="icon-btn" data-action="new-lead" data-stage="${stage}">+</button></div>${items.map(card).join('')||'<div class="empty">Sem leads nesta fase.</div>'}</section>`}).join('')}</div>`;}
function renderTable(leads){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Lead</th><th>Estado</th><th>Serviço</th><th>Origem</th><th>Valor</th><th>Responsável</th><th>Próxima ação</th><th>Ações</th></tr></thead><tbody>${leads.map(l=>`<tr><td><div class="identity"><span class="avatar">${escapeHTML(initials(l.company||l.name))}</span><div><strong>${escapeHTML(l.name)}</strong><br><span class="text-secondary">${escapeHTML(l.company)}</span></div></div></td><td><span class="status ${statusClass(l.stage)}">${escapeHTML(l.stage)}</span></td><td>${escapeHTML(l.interest||'—')}</td><td>${escapeHTML(l.source||'—')}</td><td>${money(l.estimatedBudget)}</td><td>${escapeHTML(l.owner||'—')}</td><td>${dateShort(l.deadline)}</td><td><div class="actions"><button class="icon-btn" data-action="view-lead" data-id="${l.id}">Ver</button><button class="icon-btn" data-action="edit-lead" data-id="${l.id}">Editar</button><button class="icon-btn" data-action="duplicate-lead" data-id="${l.id}">Duplicar</button><button class="icon-btn" data-action="lose-lead" data-id="${l.id}">Perdido</button><button class="icon-btn" data-action="delete-lead" data-id="${l.id}">Eliminar</button></div></td></tr>`).join('')}</tbody></table></div>`;}
function detail(lead){drawer(lead.company||lead.name, `<div class="identity"><span class="avatar">${escapeHTML(initials(lead.company||lead.name))}</span><div><h2>${escapeHTML(lead.name)}</h2><p class="text-secondary">${escapeHTML(lead.email||'Sem email')} · ${escapeHTML(lead.phone||'Sem telefone')}</p></div></div><div class="tabs">${['Visão geral','Contactos','Histórico','Notas','Próximas ações','Proposta','Atividades'].map((t,i)=>`<button class="tab ${i===0?'active':''}">${t}</button>`).join('')}</div><div class="detail-grid"><div class="detail-box"><small>Estado</small><strong>${escapeHTML(lead.stage)}</strong></div><div class="detail-box"><small>Valor potencial</small><strong>${money(lead.estimatedBudget)}</strong></div><div class="detail-box"><small>Serviço</small><strong>${escapeHTML(lead.interest||'—')}</strong></div><div class="detail-box"><small>Próxima ação</small><strong>${escapeHTML(lead.nextAction||'—')} · ${dateShort(lead.deadline)}</strong></div></div><div class="card dashboard-spaced"><h3>Notas</h3><p>${escapeHTML(lead.notes||'Sem notas.')}</p></div><div class="actions"><button class="btn" data-action="edit-lead" data-id="${lead.id}">Editar</button><button class="btn primary" data-action="convert-lead" data-id="${lead.id}">Converter em cliente</button><button class="btn" data-action="new-project-from-lead" data-id="${lead.id}">Criar projeto</button></div>`);}
async function convert(lead){const duplicate=state.clients.find(c=>(lead.email&&c.email===lead.email)||(lead.phone&&c.phone===lead.phone)); if(duplicate){toast('Já existe um cliente com este email ou telefone.', 'warning'); return;} if(!confirm(`Converter ${lead.company} em cliente?`)) return; const client={id:createId('cli'),name:lead.name,company:lead.company,email:lead.email,phone:lead.phone,whatsapp:lead.whatsapp,status:'Cliente ativo',source:'Lead convertido',notes:lead.notes,plan:lead.interest,monthlyValue:0,createdAt:new Date().toISOString(),demo:false}; await put('clients',client); await put('leads',{...lead,stage:'Ganho',convertedClientId:client.id}); await activity(`Lead convertido em cliente: ${lead.company}`,lead.id); toast('Lead convertido em cliente.', 'success'); close(); await load(); if(confirm('Abrir novo cliente agora?')) location.href='clientes.html';}
function render(){const leads=filtered(); const root=document.querySelector('#pageContent'); root.innerHTML=`<section class="page-head"><div><span class="badge">CRM comercial</span><h1>Leads</h1><p>Funil comercial Kanban com drag and drop, conversão para cliente e persistência local.</p></div><div class="actions"><div class="view-switch"><button class="btn ${state.view==='kanban'?'active':''}" data-action="view-kanban">Kanban</button><button class="btn ${state.view==='table'?'active':''}" data-action="view-table">Tabela</button></div><button class="btn primary" data-action="new-lead">Novo lead</button></div></section><section class="grid kpis">${kpis().map(([a,b,c])=>`<article class="card stat-card"><div><small>${a}</small><strong>${b}</strong><span>${c}</span></div><div class="stat-icon">◇</div></article>`).join('')}</section><section class="card dashboard-spaced"><div class="toolbar"><input id="leadSearch" value="${escapeHTML(state.query)}" placeholder="Pesquisar leads…"><select id="leadStage">${options(stages,state.stage)}</select><select id="leadSource">${options(state.leads.map(l=>l.source),state.source)}</select><select id="leadInterest">${options(state.leads.map(l=>l.interest),state.interest)}</select><select id="leadOwner">${options(state.leads.map(l=>l.owner),state.owner)}</select><select id="leadSort"><option value="createdAt">Recentes</option><option value="value" ${state.sort==='value'?'selected':''}>Valor</option><option value="deadline" ${state.sort==='deadline'?'selected':''}>Prazo</option></select></div>${state.view==='kanban'?renderKanban(leads):renderTable(leads)}</section>`; bindDnD(root);}
function bindDnD(root){root.querySelectorAll('.kanban-card').forEach(el=>el.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',el.dataset.id))); root.querySelectorAll('.kanban-column').forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault(); col.classList.add('drag-over');}); col.addEventListener('dragleave',()=>col.classList.remove('drag-over')); col.addEventListener('drop',async e=>{e.preventDefault(); col.classList.remove('drag-over'); const lead=state.leads.find(l=>l.id===e.dataTransfer.getData('text/plain')); if(lead&&lead.stage!==col.dataset.stage){await put('leads',{...lead,stage:col.dataset.stage}); await activity(`Lead movido para ${col.dataset.stage}: ${lead.company}`, lead.id); toast('Estado do lead atualizado.','success'); await load();}});});}
async function load(){state.leads=await getAll('leads'); state.clients=await getAll('clients'); render();}
function close(){document.querySelector('.drawer-backdrop')?.remove();}
export async function renderLeadsPage(container){container.innerHTML='<div class="skeleton"></div>'; await load(); if(new URLSearchParams(location.search).get('action')==='new') openEditor(); container.addEventListener('input',e=>{if(e.target.id==='leadSearch'){state.query=e.target.value;render();}}); container.addEventListener('change',e=>{if(e.target.id==='leadStage')state.stage=e.target.value;if(e.target.id==='leadSource')state.source=e.target.value;if(e.target.id==='leadInterest')state.interest=e.target.value;if(e.target.id==='leadOwner')state.owner=e.target.value;if(e.target.id==='leadSort')state.sort=e.target.value;render();}); container.addEventListener('click',async e=>{const b=e.target.closest('[data-action]'); if(!b)return; const lead=state.leads.find(l=>l.id===b.dataset.id); if(b.dataset.action==='new-lead')openEditor(null,b.dataset.stage||'Novo'); if(b.dataset.action==='view-kanban'){state.view='kanban';render();} if(b.dataset.action==='view-table'){state.view='table';render();} if(b.dataset.action==='view-lead'&&lead)detail(lead); if(b.dataset.action==='edit-lead'&&lead)openEditor(lead); if(b.dataset.action==='duplicate-lead'&&lead){await put('leads',{...lead,id:createId('lead'),name:`${lead.name} (cópia)`,createdAt:new Date().toISOString(),convertedClientId:null}); await activity(`Lead duplicado: ${lead.company}`,lead.id); toast('Lead duplicado.','success'); await load();} if(b.dataset.action==='lose-lead'&&lead){await put('leads',{...lead,stage:'Perdido'}); await activity(`Lead marcado como perdido: ${lead.company}`,lead.id); await load();} if(b.dataset.action==='delete-lead'&&lead&&confirm(`Eliminar ${lead.company}?`)){await remove('leads',lead.id); await activity(`Lead eliminado: ${lead.company}`,lead.id); toast('Lead eliminado.','success'); await load();} if(b.dataset.action==='convert-lead'&&lead)await convert(lead); if(b.dataset.action==='new-project-from-lead'&&lead)location.href=`projetos.html?lead=${lead.id}`;});}
window.addEventListener('click',e=>{if(e.target.closest('[data-action="close-drawer"]')||e.target.classList.contains('drawer-backdrop')) close();});
